### PR TITLE
add a install step on readme

### PR DESCRIPTION
**Pull request by herminiotorres**
I lost a minutes to figure out how I install.

So I proposal create a step on readme show how install

### CODE REVIEW

**Comment by themightychris** [comment]
@herminiotorres thanks! I agree that it is better to pull an Install section out to the front of the README like you did here. Would you mind adding another commit deleting the same line from the Example section?

**Review by themightychris — CHANGES_REQUESTED** [review]
delete install line from example

**Comment by herminiotorres** [comment]
@themightychris done, sorry for my delay to create a new commit remove the install step from example section!

**Comment by herminiotorres** [comment]
@themightychris ?!

**Review by themightychris — APPROVED** [review]

**Pull request merged**
